# Which backend to use
LIBDNN_BACKEND ?= sonic

# The maximum allowable tile size, used for tile and lea backends
LIBDNN_TILE_SIZE ?= 5

# The word size for data, changes how sparse blas functions operate
LIBDNN_BITWIDTH ?= 16

# Removes/adds in loops that wait for device to die
LIBDNN_INTERMITTENT ?=

# Prints out helpful debugging information when defined
LIBDNN_CONSOLE ?=

# Use the LEA Backend
LIBDNN_LEA ?=

# Profile LibDNN
LIBDNN_PROFILE ?=

# Size of the matrix buffer
LIBDNN_MAT_BUF_SIZE = 0x310

# Size of the layer buffer
LIBDNN_LAYER_BUF_SIZE ?= 0x3000

# Enable, disable, or choose DMA
LIBDNN_DMA ?= 2
