# Configuration variables and their default values
# Set these in application top-level build makefile.

# The backend for I/O (e.g. 'hwuart', 'swuart', etc.)
# See 'ls console_*.c' for available implementations.
LIBIO_BACKEND ?=

# Include functionality for outputing data to console
LIBIO_OUT ?= 1

# Include functionality for receiving data from console
LIBIO_IN ?= 0
